name: Deploy Staging

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      github-environment: staging
      vercel-environment: preview
      docker-channel: staging
      railway-environment-name: staging
      deploy-api: true
      deploy-web: true
    secrets: inherit
