name: Deploy Dev

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      github-environment: dev
      vercel-environment: preview
      docker-channel: dev
      railway-environment-name: development
      deploy-api: true
      deploy-web: true
    secrets: inherit
